import { adminAssetUrl } from "./admin-assets";

const clone = (value) => JSON.parse(JSON.stringify(value));

export const RequiredOptionsSizes = {
  items: [
    {
      id: "size-panel-small",
      label: "300 x 200 mm",
      width: 300,
      height: 200,
      isDefault: true,
      maxTextChar: -1,
      numberOfLines: -1,
    },
    {
      id: "size-panel-medium",
      label: "400 x 300 mm",
      width: 400,
      height: 300,
      isDefault: false,
      maxTextChar: -1,
      numberOfLines: -1,
    },
    {
      id: "size-panel-large",
      label: "600 x 400 mm",
      width: 600,
      height: 400,
      isDefault: false,
      maxTextChar: -1,
      numberOfLines: -1,
    },
    {
      id: "size-panel-xl",
      label: "800 x 600 mm",
      width: 800,
      height: 600,
      isDefault: false,
      maxTextChar: -1,
      numberOfLines: -1,
    },
    {
      id: "size-panel-xxl",
      label: "1000 x 700 mm",
      width: 1000,
      height: 700,
      isDefault: false,
      maxTextChar: -1,
      numberOfLines: -1,
    },
  ],
  label: "Sizes",
  thickness: {
    active: false,
    values: [],
  },
  customSize: {
    width: {
      max: 1000,
      min: 0,
      label: "Width",
    },
    active: false,
    height: {
      max: 1000,
      min: 0,
      label: "Height",
    },
    hideSizes: false,
  },
  description: "",
};

export const RequiredOptionsColors = {
  items: [
    {
      id: "color-panel-white",
      name: "White",
      pattern: {
        url: "",
        active: false,
        codeHex: "#FFFFFF",
      },
      prevImg: "",
      isDefault: true,
      textColor: {
        name: "White",
        active: true,
        codeHex: "#000000",
        sameForBorder: true,
      },
      additionalPrice: 0,
      excludeMaterials: [],
    },
    {
      id: "color-panel-black",
      name: "Black",
      pattern: {
        url: "",
        active: false,
        codeHex: "#111827",
      },
      prevImg: "",
      isDefault: false,
      textColor: {
        name: "Black",
        active: true,
        codeHex: "#ffffff",
        sameForBorder: true,
      },
      additionalPrice: 0,
      excludeMaterials: [],
    },
    {
      id: "color-panel-blue",
      name: "Blue",
      pattern: {
        url: "",
        active: false,
        codeHex: "#1D4ED8",
      },
      prevImg: "",
      isDefault: false,
      textColor: {
        name: "Blue",
        active: true,
        codeHex: "#ffffff",
        sameForBorder: true,
      },
      additionalPrice: 0,
      excludeMaterials: [],
    },
    {
      id: "color-panel-red",
      name: "Red",
      pattern: {
        url: "",
        active: false,
        codeHex: "#DC2626",
      },
      prevImg: "",
      isDefault: false,
      textColor: {
        name: "Red",
        active: true,
        codeHex: "#ffffff",
        sameForBorder: true,
      },
      additionalPrice: 0,
      excludeMaterials: [],
    },
    {
      id: "color-panel-gold",
      name: "Gold",
      pattern: {
        url: "",
        active: false,
        codeHex: "#C99700",
      },
      prevImg: "",
      isDefault: false,
      textColor: {
        name: "Gold",
        active: true,
        codeHex: "#ffffff",
        sameForBorder: true,
      },
      additionalPrice: 6,
      excludeMaterials: [],
    },
  ],
  label: "Colors",
  description: "",
  customColors: {
    label: "Custom Colors",
    active: true,
    prevImg: "",
  },
};

export const RequiredOptionsShapes = {
  items: [
    
    {
      id: "shape-square",
      label: "Square",
      shapeId: "shape-square",
      surface: 0,
      isDefault: false,
      shapeSize: {
        large: 0,
        small: 0,
        medium: 0,
      },
      additionalPrice: 0,
      excludeMaterials: [],
      enablePricingBySurface: false,
    },
    {
      id: "shape-rounded-sides",
      label: "Rounded Sides",
      shapeId: "shape-rounded-sides",
      surface: 0,
      isDefault: false,
      shapeSize: {
        large: 0,
        small: 0,
        medium: 0,
      },
      additionalPrice: 8,
      excludeMaterials: [],
      enablePricingBySurface: false,
    },
    {
      id: "shape-oval",
      label: "Oval",
      shapeId: "shape-oval",
      surface: 0,
      isDefault: false,
      shapeSize: {
        large: 0,
        small: 0,
        medium: 0,
      },
      additionalPrice: 12,
      excludeMaterials: [],
      enablePricingBySurface: false,
    },
  ],
  label: "Shapes",
  description: "",
};

export const RequiredOptionsFixingMethods = {
  items: [
    {
      id: "fixing-table-stand",
      label: "Table Stand",
      isDefault: true,
      isVisible: true,
      previewImg: "",
      description: "",
      excludeSizes: [],
      excludeShapes: [],
      fixingMethodId: "table-stand",
      additionalPrice: 0,
      excludeMaterials: [],
    },
    {
      id: "fixing-ceiling",
      label: "Ceiling",
      isDefault: false,
      isVisible: true,
      previewImg: "",
      description: "",
      excludeSizes: [],
      excludeShapes: [],
      fixingMethodId: "ceiling",
      additionalPrice: 0,
      excludeMaterials: [],
    },
    {
      id: "fixing-pole-attachment",
      label: "Pole Attachment",
      isDefault: false,
      isVisible: true,
      previewImg: "",
      description: "",
      excludeSizes: [],
      excludeShapes: [],
      fixingMethodId: "pole-attachment",
      additionalPrice: 10,
      excludeMaterials: [],
    },
    {
      id: "fixing-cable-labeling",
      label: "Cable Labeling",
      isDefault: false,
      isVisible: true,
      previewImg: "",
      description: "",
      excludeSizes: [],
      excludeShapes: [],
      fixingMethodId: "cable-labeling",
      additionalPrice: 4,
      excludeMaterials: [],
    },
    {
      id: "fixing-table-clamp",
      label: "Table Clamp",
      isDefault: false,
      isVisible: true,
      previewImg: "",
      description: "",
      excludeSizes: [],
      excludeShapes: [],
      fixingMethodId: "table-clamp",
      additionalPrice: 18,
      excludeMaterials: [],
    },
  ],
  label: "Fixing Methods",
  description: "",
};

export const RequiredOptionsBorders = {
  items: [
    {
      id: "border-standard",
      label: "Standard border",
      isDefault: true,
      excludeSizes: [],
      excludeShapes: [],
      borderId: "border-normal",
      additionalPrice: 0,
    },
    {
      id: "border-rounded",
      label: "Rounded corners",
      isDefault: false,
      excludeSizes: [],
      excludeShapes: [],
      borderId: "border-rounded-corners",
      additionalPrice: 6,
    },
    {
      id: "border-premium",
      label: "Old World",
      isDefault: false,
      excludeSizes: [],
      excludeShapes: [],
      borderId: "border-old-world",
      additionalPrice: 10,
    },
    {
      id: "border-double-line",
      label: "None",
      isDefault: false,
      excludeSizes: [],
      excludeShapes: [],
      borderId: "border-none",
      additionalPrice: 8,
    },
  ],
  label: "Borders",
  settings: {
    colors: [
      {
        id: "border-color-white",
        name: "White",
        codeHex: "#FFFFFF",
        additionalPrice: 0,
      },
      {
        id: "border-color-black",
        name: "Black",
        codeHex: "#000000",
        additionalPrice: 0,
      },
      {
        id: "border-color-blue",
        name: "Blue",
        codeHex: "#004f86",
        additionalPrice: 0,
      },
      {
        id: "border-color-red",
        name: "Red",
        codeHex: "#c4271d",
        additionalPrice: 0,
      },
      {
        id: "border-color-green",
        name: "Green",
        codeHex: "#009251",
        additionalPrice: 0,
      },
      {
        id: "border-color-yellow",
        name: "Yellow",
        codeHex: "#fee900",
        additionalPrice: 0,
      },
      {
        id: "border-color-gray",
        name: "Gray",
        codeHex: "#4f5756",
        additionalPrice: 0,
      },
      {
        id: "border-color-pink",
        name: "Pink",
        codeHex: "#bc4077",
        additionalPrice: 0,
      },
      {
        id: "border-color-purple",
        name: "Purple",
        codeHex: "#554585",
        additionalPrice: 0,
      },
      {
        id: "border-color-orange",
        name: "Orange",
        codeHex: "#e15616",
        additionalPrice: 0,
      },
      {
        id: "border-color-brown",
        name: "Brown",
        codeHex: "#523d2a",
        additionalPrice: 0,
      },
    ],
    borderColorsLabel: "Borders Colors",
    enableBorderColor: true,
    enableBorderWidth: true,
    customColorsPrevImg: "",
  },
  description: "",
};

export const RequiredOptionsPricings = {
  mode: "frame-fit",
  label: "Pricings",
  description: "Starter pricing presets for signs and panels.",
  items: [
    {
      id: "pricing-signs-standard",
      label: "Standard panel pricing",
      customPricing: {
        type: "unit",
        unit: {
          surface: 60000,
          basePrice: 24,
          charPrice: 0,
        },
        range: [],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
    {
      id: "pricing-banner-standard",
      label: "Standard banner pricing",
      customPricing: {
        type: "unit",
        unit: {
          surface: 80000,
          basePrice: 18,
          charPrice: 0,
        },
        range: [],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
    {
      id: "pricing-banner-premium",
      label: "Premium banner pricing",
      customPricing: {
        type: "unit",
        unit: {
          surface: 120000,
          basePrice: 26,
          charPrice: 0,
        },
        range: [],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
    {
      id: "pricing-sticker-standard",
      label: "Standard sticker pricing",
      customPricing: {
        type: "unit",
        unit: {
          surface: 20000,
          basePrice: 12,
          charPrice: 0,
        },
        range: [],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
    {
      id: "pricing-sticker-premium",
      label: "Premium sticker pricing",
      customPricing: {
        type: "unit",
        unit: {
          surface: 40000,
          basePrice: 19,
          charPrice: 0,
        },
        range: [],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
    {
      id: "pricing-signs-acrylic",
      label: "Premium acrylic pricing",
      customPricing: {
        type: "unit",
        unit: {
          surface: 80000,
          basePrice: 38,
          charPrice: 0,
        },
        range: [],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
    {
      id: "pricing-signs-metal",
      label: "Metal panel pricing",
      customPricing: {
        type: "unit",
        unit: {
          surface: 80000,
          basePrice: 42,
          charPrice: 0,
        },
        range: [],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
    {
      id: "pricing-signs-wood",
      label: "Wood panel pricing",
      customPricing: {
        type: "unit",
        unit: {
          surface: 70000,
          basePrice: 34,
          charPrice: 0,
        },
        range: [],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
    {
      id: "pricing-signs-large",
      label: "Large format panel pricing",
      customPricing: {
        type: "range",
        unit: {
          surface: 0,
          basePrice: 0,
          charPrice: 0,
        },
        range: [
          {
            length: 0,
            surface: 60000,
            basePrice: 28,
            charPrice: 0,
            shippingPrice: 0,
            widthModifier: 0,
            heightModifier: 0,
          },
          {
            length: 0,
            surface: 180000,
            basePrice: 46,
            charPrice: 0,
            shippingPrice: 0,
            widthModifier: 0,
            heightModifier: 0,
          },
        ],
        shippingMethod: "per-surface",
        divisorVolumetric: 5000,
        rangePricingPerUnit: false,
      },
    },
  ],
};

export const RequiredOptionsFonts = {
  label: "Fonts",
  description: "",
  items: [
    {
      id: "font-arial",
      label: "Arial",
      url: adminAssetUrl("fonts/arial.ttf"),
      previewImg: "",
      isGoogleFont: false,
      isDefault: true,
      managedFontId: 0,
    },
    {
      id: "font-allura",
      label: "Allura",
      url: adminAssetUrl("fonts/allura.ttf"),
      previewImg: "",
      isGoogleFont: true,
      isDefault: false,
      managedFontId: 1,
    },
    {
      id: "font-avante",
      label: "Avante",
      url: adminAssetUrl("fonts/avante.ttf"),
      previewImg: "",
      isGoogleFont: true,
      isDefault: false,
      managedFontId: 2,
    },
    {
      id: "font-barcelona",
      label: "Barcelona",
      url: adminAssetUrl("fonts/barcelona.ttf"),
      previewImg: "",
      isGoogleFont: true,
      isDefault: false,
      managedFontId: 3,
    },
    {
      id: "font-corinthia",
      label: "Corinthia",
      url: adminAssetUrl("fonts/corinthia.ttf"),
      previewImg: "",
      isGoogleFont: true,
      isDefault: false,
      managedFontId: 4,
    },
    {
      id: "font-type-machine",
      label: "Type Machine",
      url: adminAssetUrl("fonts/type-machine.ttf"),
      previewImg: "",
      isGoogleFont: true,
      isDefault: false,
      managedFontId: 5,
    },
  ],
};

export const AdditionalOptionsInputs = {
  items: [
    {
      id: "input-panel-installation",
      type: "yes/no",
      label: "Need installation help?",
      price: {
        type: "none",
        value: 0,
      },
      inputs: {
        no: "No",
        yes: "Yes",
      },
      default: "no",
      popupImg: "",
      description: "Ask if the customer needs installation guidance.",
    },
    {
      id: "input-panel-reference",
      type: "text",
      label: "Reference text",
      price: {
        type: "none",
        value: 0,
      },
      default: "",
      popupImg: "",
      description: "Internal or room reference to print on the sign.",
    },
    {
      id: "input-panel-logo",
      type: "yes/no",
      label: "Add logo area?",
      price: {
        type: "none",
        value: 0,
      },
      inputs: {
        no: "No",
        yes: "Yes",
      },
      default: "no",
      popupImg: "",
      description: "Allow a dedicated logo area on the sign.",
    },
    {
      id: "input-panel-delivery",
      type: "select",
      label: "Delivery urgency",
      price: {
        type: "none",
        value: 0,
      },
      inputs: {
        express: "Express",
        priority: "Priority",
        standard: "Standard",
      },
      default: "standard",
      popupImg: "",
      description: "Let the customer pick the delivery speed.",
    },
    {
      id: "input-panel-proof",
      type: "yes/no",
      label: "Need approval proof?",
      price: {
        type: "none",
        value: 0,
      },
      inputs: {
        no: "No",
        yes: "Yes",
      },
      default: "yes",
      popupImg: "",
      description:
        "Ask if the customer wants a visual proof before production.",
    },
  ],
  label: "Inputs",
  description: "",
};

const signboardComponentRules = {
  acrylic: { enabled: true },
  aluminium: { enabled: true },
  brass: { enabled: true },
  "eco-friendly": { enabled: true },
  magnet: { enabled: true },
  "photo-paper": { enabled: true },
  plastic: { enabled: true },
  "stainless-steel": { enabled: true },
  vinyl: { enabled: true },
  wood: { enabled: true },
};

export const AdditionalOptionsComponents = {
  items: [
    {
      id: "additional-component-surface-finish",
      icon: "",
      title: "Surface finish",
      options: [
        {
          id: "additional-component-surface-finish-matte",
          icon: "",
          image: "",
          title: "Matte",
          surface: 0,
          popupImg: "",
          isDefault: true,
          description: "",
          excludeColors: [],
          additionalPrice: 0,
          enablePricingBySurface: false,
        },
        {
          id: "additional-component-surface-finish-gloss",
          icon: "",
          image: "",
          title: "Gloss",
          surface: 0,
          popupImg: "",
          isDefault: false,
          description: "",
          excludeColors: [],
          additionalPrice: 8,
          enablePricingBySurface: false,
        },
      ],
      description: "Offer finish options for rigid signs and panels.",
      rulesByMaterial: signboardComponentRules,
    },
    {
      id: "additional-component-corners",
      icon: "",
      title: "Corner finish",
      options: [
        {
          id: "additional-component-corners-sharp",
          icon: "",
          image: "",
          title: "Sharp corners",
          surface: 0,
          popupImg: "",
          isDefault: true,
          description: "",
          excludeColors: [],
          additionalPrice: 0,
          enablePricingBySurface: false,
        },
        {
          id: "additional-component-corners-rounded",
          icon: "",
          image: "",
          title: "Rounded corners",
          surface: 0,
          popupImg: "",
          isDefault: false,
          description: "",
          excludeColors: [],
          additionalPrice: 6,
          enablePricingBySurface: false,
        },
      ],
      description: "Offer corner finishing options.",
      rulesByMaterial: signboardComponentRules,
    },
    {
      id: "additional-component-protective-layer",
      icon: "",
      title: "Protective layer",
      options: [
        {
          id: "additional-component-protective-layer-standard",
          icon: "",
          image: "",
          title: "Standard",
          surface: 0,
          popupImg: "",
          isDefault: true,
          description: "",
          excludeColors: [],
          additionalPrice: 0,
          enablePricingBySurface: false,
        },
        {
          id: "additional-component-protective-layer-uv",
          icon: "",
          image: "",
          title: "UV protection",
          surface: 0,
          popupImg: "",
          isDefault: false,
          description: "",
          excludeColors: [],
          additionalPrice: 10,
          enablePricingBySurface: false,
        },
      ],
      description: "Add extra protection for outdoor use.",
      rulesByMaterial: signboardComponentRules,
    },
    {
      id: "additional-component-drill-holes",
      icon: "",
      title: "Drill holes",
      options: [
        {
          id: "additional-component-drill-holes-no-holes",
          icon: "",
          image: "",
          title: "No holes",
          surface: 0,
          popupImg: "",
          isDefault: true,
          description: "",
          excludeColors: [],
          additionalPrice: 0,
          enablePricingBySurface: false,
        },
        {
          id: "additional-component-drill-holes-4-corner-holes",
          icon: "",
          image: "",
          title: "4 corner holes",
          surface: 0,
          popupImg: "",
          isDefault: false,
          description: "",
          excludeColors: [],
          additionalPrice: 5,
          enablePricingBySurface: false,
        },
      ],
      description: "Offer pre-drilled holes for installation.",
      rulesByMaterial: signboardComponentRules,
    },
    {
      id: "additional-component-texture",
      icon: "",
      title: "Texture style",
      options: [
        {
          id: "additional-component-texture-smooth",
          icon: "",
          image: "",
          title: "Smooth",
          surface: 0,
          popupImg: "",
          isDefault: true,
          description: "",
          excludeColors: [],
          additionalPrice: 0,
          enablePricingBySurface: false,
        },
        {
          id: "additional-component-texture-brushed",
          icon: "",
          image: "",
          title: "Brushed",
          surface: 0,
          popupImg: "",
          isDefault: false,
          description: "",
          excludeColors: [],
          additionalPrice: 12,
          enablePricingBySurface: false,
        },
      ],
      description: "Apply a premium texture treatment.",
      rulesByMaterial: signboardComponentRules,
    },
  ],
  label: "Additional Components",
  description: "",
};

export const RequiredOptionsLightings = {
  items: [
    {
      id: "lighting-panel-soft-white",
      label: "Soft White",
      hexCode: "#F5F5F4",
      isDefault: true,
      additionalPrice: 0,
    },
    {
      id: "lighting-panel-amber",
      label: "Amber Glow",
      hexCode: "#F59E0B",
      isDefault: false,
      additionalPrice: 4,
    },
    {
      id: "lighting-panel-warm-white",
      label: "Warm White",
      hexCode: "#FFF4D6",
      isDefault: false,
      additionalPrice: 2,
    },
    {
      id: "lighting-panel-cool-white",
      label: "Cool White",
      hexCode: "#E8F1FF",
      isDefault: false,
      additionalPrice: 3,
    },
    {
      id: "lighting-panel-rose",
      label: "Rose Glow",
      hexCode: "#F472B6",
      isDefault: false,
      additionalPrice: 5,
    },
    {
      id: "lighting-panel-neon-blue",
      label: "Neon Blue",
      hexCode: "#38BDF8",
      isDefault: false,
      additionalPrice: 5,
    },
  ],
  label: "Lighting",
  description: "",
};

const createComponentOption = ({
  componentId,
  suffix,
  label,
  sizeId,
  shape,
  border,
  fixingMethods,
  backgroundColorId,
  additionalPrice = 0,
  isDefault = false,
}) => ({
  id: `${componentId}-${suffix}`,
  icon: "",
  image: "",
  label,
  sizes: {
    items: [
      {
        id: sizeId,
        isDefault: true,
      },
    ],
  },
  shapes: {
    items: [
      {
        ...shape,
        custom: false,
        isDefault: true,
      },
    ],
  },
  borders: {
    items: [
      {
        ...border,
        custom: false,
        isDefault: true,
      },
    ],
  },
  isDefault,
  lightings: {
    items: [
      {
        id: `${componentId}-${suffix}-glow-soft`,
        label: "Soft Glow",
        hexCode: "#F4F4F5",
        isDefault: true,
        additionalPrice: 0,
      },
      {
        id: `${componentId}-${suffix}-glow-amber`,
        label: "Amber Glow",
        hexCode: "#F59E0B",
        isDefault: false,
        additionalPrice: 4,
      },
    ],
    customColorLabel: "Custom Color",
    enableCustomColor: false,
  },
  overrides: {
    additionalPrice,
  },
  textZones: [
    {
      x: 50,
      y: 56,
      id: `${componentId}-${suffix}-text-main`,
      bold: true,
      color: "#111827",
      label: "Main text",
      value: label,
      italic: false,
      fontSize: 42,
      textAlign: "center",
      defaultFont: "Arial",
    },
    {
      x: 50,
      y: 76,
      id: `${componentId}-${suffix}-text-sub`,
      bold: false,
      color: "#475467",
      label: "Subtitle",
      value: label.split(" ").slice(0, -1).join(" ") || label,
      italic: false,
      fontSize: 18,
      textAlign: "center",
      defaultFont: "Arial",
    },
  ],
  imageZones: [
    {
      x: 50,
      y: 24,
      id: `${componentId}-${suffix}-image-logo`,
      tint: "#111827",
      image: "/aso_default_files/demos/logo.webp",
      label: "Logo",
      width: 96,
      height: 96,
      fitMode: "contain",
      lockAspectRatio: true,
    },
  ],
  backgrounds: {
    items: [
      {
        id: backgroundColorId,
        isDefault: true,
      },
    ],
    customColorLabel: "Custom Color",
    enableCustomColor: false,
  },
  description: `${label} preset.`,
  fixingMethods: {
    items: fixingMethods,
  },
});

const rectangleShape = {
  id: "shape-rectangle",
  url: "/aso_default_files/demos/shape-preview.svg",
  label: "Rectangle",
  shapeId: "shape-rectangle",
  additionalPrice: 0,
};

const squareShape = {
  id: "shape-square",
  url: "/aso_default_files/demos/shape-preview.svg",
  label: "Square",
  shapeId: "shape-square",
  additionalPrice: 0,
};

const standardBorder = {
  id: "border-standard",
  url: "/aso_default_files/demos/border-preview.svg",
  label: "Standard border",
  description: "",
  borderId: "border-normal",
  additionalPrice: 0,
};

const roundedBorder = {
  id: "border-rounded",
  url: "/aso_default_files/demos/border-preview.svg",
  label: "Rounded corners",
  description: "",
  borderId: "border-rounded-corners",
  additionalPrice: 6,
};

const fixingWallScrews = (sizeId, isDefault = true) => ({
  id: "fixing-wall-screws",
  url: "/aso_default_files/demos/fixing-preview.svg",
  label: "Wall screws",
  custom: false,
  sizeId,
  isDefault,
  description: "",
  fixingMethodId: "fixing-screw",
  additionalPrice: 0,
});

const fixingHangingKit = (sizeId, isDefault = false) => ({
  id: "fixing-hanging-kit",
  url: "/aso_default_files/demos/fixing-preview.svg",
  label: "Hanging kit",
  custom: false,
  sizeId,
  isDefault,
  description: "",
  fixingMethodId: "fixing-hanging",
  additionalPrice: 0,
});

const fixingStandoffKit = (sizeId, isDefault = false) => ({
  id: "fixing-standoff-kit",
  url: "/aso_default_files/demos/fixing-preview.svg",
  label: "Standoff kit",
  custom: false,
  sizeId,
  isDefault,
  description: "",
  fixingMethodId: "fixing-stand-off",
  additionalPrice: 10,
});

export const RequiredOptionsComponentsAdvanced = {
  items: [
    {
      id: "component-panel-office",
      icon: "",
      label: "Office plaque",
      name: "Office plaque",
      title: "Office plaque",
      options: [
        createComponentOption({
          componentId: "component-panel-office",
          suffix: "office-plaque-standard",
          label: "Office plaque Standard",
          sizeId: "size-panel-small",
          shape: rectangleShape,
          border: standardBorder,
          fixingMethods: [
            fixingWallScrews("size-panel-small", true),
            fixingHangingKit("size-panel-small", false),
          ],
          backgroundColorId: "color-panel-white",
          isDefault: true,
        }),
        createComponentOption({
          componentId: "component-panel-office",
          suffix: "office-plaque-premium",
          label: "Office plaque Premium",
          sizeId: "size-panel-medium",
          shape: squareShape,
          border: roundedBorder,
          fixingMethods: [
            fixingHangingKit("size-panel-medium", true),
            fixingStandoffKit("size-panel-medium", false),
          ],
          backgroundColorId: "color-panel-black",
          additionalPrice: 8,
        }),
      ],
      isDefault: true,
      isVisible: true,
      description: "Ready combination for office door and desk signs.",
    },
    {
      id: "component-panel-directional",
      icon: "",
      label: "Directional sign",
      name: "Directional sign",
      title: "Directional sign",
      options: [
        createComponentOption({
          componentId: "component-panel-directional",
          suffix: "directional-sign-wall-mount",
          label: "Directional sign Wall mount",
          sizeId: "size-panel-medium",
          shape: rectangleShape,
          border: standardBorder,
          fixingMethods: [
            fixingWallScrews("size-panel-medium", true),
            fixingHangingKit("size-panel-medium", false),
          ],
          backgroundColorId: "color-panel-white",
          isDefault: true,
        }),
        createComponentOption({
          componentId: "component-panel-directional",
          suffix: "directional-sign-standoff",
          label: "Directional sign Standoff",
          sizeId: "size-panel-large",
          shape: squareShape,
          border: roundedBorder,
          fixingMethods: [
            fixingStandoffKit("size-panel-large", true),
            fixingHangingKit("size-panel-large", false),
          ],
          backgroundColorId: "color-panel-blue",
          additionalPrice: 8,
        }),
      ],
      isDefault: false,
      isVisible: true,
      description: "Preset combinations for directional and wayfinding signs.",
    },
  ],
  label: "Components",
  settings: {
    label: "Components",
    tabIcon: "",
    behavior: "show-options-directly",
    description: "Choose your design",
    emptyStateMessage: "No designs available.",
    showTabWhenSingleItem: true,
  },
  description: "",
};

export const configurationDemoData = [
  {
    data: {
      settings: {
        generals: {
          mobile: {
            showNavigatorMenu: "off",
            showNavigationMenuFirst: "yes",
            mobileSelectionOptionsDisplay: "horizontally",
          },
          output: {
            waterMark: "",
            filesFormat: "png",
            zipOutputFiles: {
              active: true,
              zipOutFolderPrefix: "aso_",
            },
            designComposition: true,
          },
          upload: {
            zipFiles: {
              active: false,
              zipOutFolderPrefix: "aso_",
            },
            allowFormat: "jpg,jpeg,png,gif,bmp,tiff,webp,psd,ai,svg,eps,pdf",
            maxUploadSize: 5000,
            maxUploadNumber: 5,
          },
          product: {
            hidePricing: false,
            designFromScratch: true,
            showRecapAfterFinish: true,
            redirectToCheckOutPage: false,
            displayRecapsOnCheckout: false,
            redirectAfterAddingToCart: true,
            hideDesignButtonsOnShopPage: false,
            hideAddToCartButtonOnShopPage: true,
            hideAddToCartButtonOnDetailPage: true,
          },
        },
        themeColors: {
          skin: "default",
          colors: {
            bars: {
              help: {
                textColor: "#ffffff",
                borderColor: "#016464",
                hoverTextColor: "#ffffff",
                backgroundColor: "#016464",
                hoverBorderColor: "#016464",
                hoverBackgroundColor: "#016464",
              },
              price: {
                textColor: "#000000",
                textAfterColor: "#000000",
                backgroundColor: "#ffffff",
                textBeforeColor: "#000000",
              },
              reset: {
                textColor: "#000000",
                borderColor: "#ffffff",
                hoverTextColor: "#dd3232",
                modalTextColor: "#000000",
                backgroundColor: "#ffffff",
                hoverBorderColor: "#f4f8fa",
                hoverBackgroundColor: "#f4f8fa",
                modalBackgroundColor: "#000000",
                modalNoButtonTextColor: "#ffffff",
                modalYesButtonTextColor: "#000000",
                modalContainerBackground: "#ffffff",
                modalNoButtonBackgroundColor: "#dc2626",
                modalYesButtonBackgroundColor: "#f4f8fa",
              },
              preview: {
                textColor: "#000000",
                borderColor: "#ffffff",
                hoverTextColor: "#016464",
                backgroundColor: "#ffffff",
                hoverBorderColor: "#f4f8fa",
                hoverBackgroundColor: "#f4f8fa",
              },
              undoRedo: {
                textColor: "#000000",
                borderColor: "#ffffff",
                hoverTextColor: "#016464",
                backgroundColor: "#ffffff",
                hoverBorderColor: "#f4f8fa",
                disabledTextColor: "#c3cfd6",
                hoverBackgroundColor: "#f4f8fa",
                disabledBackgroundColor: "#ffffff",
              },
              titleColor: "#000000",
              backgroundColor: "#ffffff",
            },
            canvas: {
              borderColor: "#c3cfd6",
              backgroundColor: "#f4f8fa",
            },
            recaps: {
              backgroundColor: "#ffffff",
              headerTextColor: "#ffffff",
              optionTextColor: "#000000",
              optionBorderColor: "#eef3f6",
              buttonEditTextColor: "#ffffff",
              optionHoverTextColor: "#000000",
              buttonFinishTextColor: "#14213d",
              headerBackgroundColor: "#058585",
              optionHoverBorderColor: "#eef3f6",
              buttonAddToCartTextColor: "#14213d",
              buttonEditHoverTextColor: "#f4f8fa",
              buttonEditBackgroundColor: "#016464",
              buttonFinishHoverTextColor: "#313e52",
              optionHoverBackgroundColor: "#eef3f6",
              buttonFinishBackgroundColor: "#febd52",
              buttonAddToCartHoverTextColor: "#313e52",
              buttonAddToCartBackgroundColor: "#febd52",
              buttonEditHoverBackgroundColor: "#058585",
              buttonFinishHoverBackgroundColor: "#fcac29",
              buttonAddToCartHoverBackgroundColor: "#fcac29",
            },
            objectsOptions: {
              edit: {
                textColor: "#000000",
                buttonColor: "#ffffff",
                hoverTextColor: "#ffffff",
                hoverButtonColor: "#787878",
              },
              clone: {
                textColor: "#000000",
                buttonColor: "#ffffff",
                hoverTextColor: "#ffffff",
                hoverButtonColor: "#787878",
              },
              center: {
                textColor: "#000000",
                buttonColor: "#ffffff",
                hoverTextColor: "#ffffff",
                hoverButtonColor: "#787878",
              },
              delete: {
                textColor: "#dd3232",
                buttonColor: "#ffffff",
                hoverTextColor: "#dd3232",
                hoverButtonColor: "#787878",
              },
              backgroundColor: "#ffffff",
            },
            optionsSideBar: {
              options: {
                modals: {
                  option: {
                    textColor: "#000000",
                    hoverTextColor: "#000000",
                    activeTextColor: "#016464",
                    hoverBackgroundColor: "#eef3f6",
                  },
                  buttons: {
                    textColor: "#ffffff",
                    hoverTextColor: "#ffffff",
                    backgroundColor: "#016464",
                    hoverBackgroundColor: "#028383",
                  },
                  textColor: "#000000",
                  backgroundColor: "#ffffff",
                  headerTextColor: "#ffffff",
                  headerBackgroundColor: "#016464",
                },
                buttons: {
                  textColor: "#000000",
                  hoverTextColor: "#016464",
                  hovertextColor: "#016464",
                  backgroundColor: "#ffffff",
                  hoverBackgroundColor: "#ffffff",
                },
              },
              backgroundColor: "#eef3f6",
              scrollButtonsTextColor: "#ffffff",
              scrollButtonsHoverTextColor: "#ffffff",
              scrollButtonsBackgroundColor: "#4a4a4a",
              scrollButtonsHoverBackgroundColor: "#74848d",
            },
          },
          customCss: "",
        },
        customizerSign: {
          text: {
            colors: [
              {
                id: "sign-text-color-black",
                name: "black",
                codeHex: "#000000",
              },
              {
                id: "sign-text-color-white",
                name: "White",
                codeHex: "#FFFFFF",
              },
              {
                id: "sign-text-color-blue",
                name: "Blue",
                codeHex: "#004f86",
              },
              {
                id: "sign-text-color-red",
                name: "Red",
                codeHex: "#c4271d",
              },
              {
                id: "sign-text-color-pink",
                name: "Pink",
                codeHex: "#eb3f77",
              },
              {
                id: "sign-text-color-green",
                name: "Green",
                codeHex: "#009251",
              },
              {
                id: "sign-text-color-yellow",
                name: "Yellow",
                codeHex: "#fee900",
              },
              {
                id: "sign-text-color-gray",
                name: "Gray",
                codeHex: "#4f575b",
              },
              {
                id: "sign-text-color-orange",
                name: "Orange",
                codeHex: "#e15616",
              },
              {
                id: "sign-text-color-purple",
                name: "Purple",
                codeHex: "#554585",
              },
              {
                id: "sign-text-color-brown",
                name: "Brown",
                codeHex: "#523d2a",
              },
            ],
            textType: "normal",
            enableBold: true,
            colorsLabel: "Text  Colors",
            enableBorder: true,
            enableItalic: true,
            enableStrike: true,
            colorsPrevImg: "",
            enableOpacity: true,
            selectedFonts: [0, 1, 2],
            enableCurvedUp: false,
            enableFontSize: {
              active: true,
              defaultFontSize: 16,
              maximumFontSize: 100,
              minimumFontSize: 4,
            },
            enableOverline: true,
            enableUnderline: true,
            enableCurvedDown: false,
            enableCustomColor: true,
            enableTextAlignment: true,
          },
          images: {
            colors: [],
            filter: {
              active: true,
              enableBlur: true,
              enableSepia: true,
              enableEmbross: true,
              enableOpacity: true,
              enableSharpen: true,
              enableGreyscale: false,
            },
            scenes: [],
            colorsLabel: "Image Colors",
            colorsPrevImg: "",
            enableClipart: {
              active: true,
              selectClipartGroups: [1],
            },
            fileUploadScript: {
              uploadMaxWidth: 200,
              uploadMinWidth: 10,
              customWithGraphical: false,
              enableSizeRestriction: false,
              allowedUploadsExtentions: ["png"],
            },
            enableCustomColor: true,
            enableUploadImage: true,
            enableDownloadImage: true,
          },
          signPart: {
            doublePart: {
              label: "Switch Face",
              part1: "Face A",
              part2: "Face B",
              active: false,
              enableCopyDesignFromSide: true,
            },
          },
          configOptions: [
            {
              type: "materials",
              active: true,
            },
            {
              type: "sizes",
              active: true,
            },
            {
              type: "shapes",
              active: true,
            },
            {
              type: "fixing-methodes",
              active: true,
            },
            {
              type: "borders",
              active: true,
            },
            {
              type: "colors",
              active: true,
            },
            {
              type: "texts",
              active: true,
            },
            {
              type: "qrcodes",
              active: true,
            },
            {
              type: "images",
              active: true,
            },
            {
              type: "additional-options",
              active: true,
            },
            {
              type: "additional-components",
              active: true,
            },
          ],
          customizerOptions: {
            allowNextButton: false,
            measurementUnit: "mm",
            desktopColumnOrder: "right",
            finishButtonPosition: "bottom",
            showHideMeasurements: "both",
            showThicknessPricing: false,
            expandThicknessByDefault: false,
            decimalFormatMeasurements: "with-decimal",
            expandPredefinedSizesByDefault: false,
          },
        },
        languageImages: {
          images: {
            redoIcon: "",
            undoIcon: "",
            resetAllIcon: "",
            cancelAnAction: "",
            changeIconHelp: "",
            changeIconSize: "",
            changeIconText: "",
            changeIconColor: "",
            changeIconImage: "",
            changeIconShape: "",
            changeIconShare: "",
            changeIconBorder: "",
            changeIconImport: "",
            changeIconPreview: "",
            changeIconProduct: "",
            changeIconDownload: "",
            changeIconMaterial: "",
            changeIconSaveProject: "",
            changeIconFixingMethod: "",
            changeIconShareSideBar: "",
          },
          visualizer: {
            textTop: "Top",
            textHelp: "Help",
            textLeft: "Left",
            textSave: "Save",
            textSize: "Size",
            textAngle: "Angle",
            textColor: "Color",
            textImage: "Image",
            textRight: "Right",
            textShape: "Shape",
            textShare: "Share",
            textWidth: "Width",
            thickness: "Thickness",
            customSize: "Custom Size",
            textBorder: "Border",
            textBottom: "Bottom",
            textHeight: "Height",
            textImport: "Import",
            textPreview: "Preview",
            textProduct: "Product",
            titleHeader: "Design your own sign",
            textDownload: "Download",
            textMaterial: "Material",
            textPosition: "Position",
            textAddToCart: "Add To Cart",
            textAfterPrice: "TVA Include",
            textButtonBack: "Undo",
            textButtonNext: "Redo",
            textCanvasEdit: "Edit",
            textOptionText: "Text",
            textBeforePrice: "",
            textCanvasClone: "Clone",
            textButtonFinish: "Finish",
            textCanvasDelete: "delete",
            textButtonRefresh: "Restart all",
            textCanvasCenterH: "centerH",
            textCanvasCenterV: "centerV",
            textFixingMethods: "Fixing Methods",
            customSizeButtonDone: "Done",
            textAdditonnalOptionsHeader: "Additionnals Options",
            textButtonAdditonnalOptions: "Add Option",
            phraseImageSizeRestrictionError: "The image size must be between",
          },
          uploadDesign: {
            link: "",
            activate: false,
            helpContent: "",
            phraseSubmitCustom: "Take a customization",
          },
        },
      },
      pricingMode: "frame-fit",
      productType: "",
      materialType: "simple",
      requiredOptions: clone({
        sizes: RequiredOptionsSizes,
        colors: RequiredOptionsColors,
        shapes: RequiredOptionsShapes,
        fixingMethods: RequiredOptionsFixingMethods,
        borders: RequiredOptionsBorders,
        pricings: RequiredOptionsPricings,
        fonts: RequiredOptionsFonts,
        lightings: RequiredOptionsLightings,
      }),
      additionalOptions: clone({
        inputs: AdditionalOptionsInputs,
        materials: {
          items: [],
          label: "Materials",
          description: "",
        },
        components: AdditionalOptionsComponents,
      }),
    },
  },
];
